# Generated by Django 6.0.2 on 2026-02-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('badge_text', models.CharField(blank=True, help_text="e.g., 'Free Delivery'", max_length=50)),
                ('link', models.CharField(default='#', help_text='Button Link', max_length=200)),
                ('position', models.CharField(choices=[('Main', 'Main Big Banner'), ('Side', 'Side Small Banner')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
