# Generated by Django 6.0.2 on 2026-02-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_latitude', models.FloatField(default=9.9312)),
                ('store_longitude', models.FloatField(default=76.2673)),
                ('max_delivery_radius_km', models.FloatField(default=10.0)),
            ],
        ),
    ]
